In [1]:
from pyremote import remote, remotecell, UvConfig, close_remote
import numpy as np

/home/husein/.local/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/husein/.local/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,


In [2]:
remote(
    "localhost", 
    "ubuntu", 
    password="ubuntu123", 
    uv=UvConfig(path="~/.venv-3.11", python_version="3.11", install_uv=True, delete_after_done=True), 
    dependencies=["numpy==1.26.4", "pandas==2.2.3", "torch==2.9.1"],
    install_verbose=True,
    jupyter_mode=True,
)

Using CPython 3.11.13 interpreter at: /usr/bin/python3.11
Creating virtual environment at: .venv-3.11
Activate with: source .venv-3.11/bin/activate
Using Python 3.11.13 environment at: .venv-3.11
Resolved 1 package in 1ms
Installed 1 package in 1ms
 + cloudpickle==3.1.2
Using Python 3.11.13 environment at: .venv-3.11
Resolved 31 packages in 7ms
Installed 31 packages in 109ms
 + filelock==3.20.3
 + fsspec==2026.2.0
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + mpmath==1.3.0
 + networkx==3.6.1
 + numpy==1.26.4
 + nvidia-cublas-cu12==12.8.4.1
 + nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-runtime-cu12==12.8.90
 + nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufile-cu12==1.13.1.3
 + nvidia-curand-cu12==10.3.9.90
 + nvidia-cusolver-cu12==11.7.3.90
 + nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparselt-cu12==0.7.1
 + nvidia-nccl-cu12==2.27.5
 + nvidia-nvjitlink-cu12==12.8.93
 + nvidia-nvshmem-cu12==3.3.20
 + nvidia-nvtx-cu12==12.8.9

In [3]:
remote(
    "localhost", 
    "ubuntu", 
    password="ubuntu123", 
    uv=UvConfig(path="~/.venv-3.10", python_version="3.10", install_uv=True, delete_after_done=True), 
    dependencies=["numpy==1.26.4", "pandas==2.2.3", "torch==2.9.1"],
    install_verbose=True,
    jupyter_mode=True,
    jupyter_profile="3.10"
)

Using CPython 3.10.17 interpreter at: /usr/bin/python3.10
Creating virtual environment at: .venv-3.10
Activate with: source .venv-3.10/bin/activate
Using Python 3.10.17 environment at: .venv-3.10
Resolved 1 package in 1ms
Installed 1 package in 1ms
 + cloudpickle==3.1.2
Using Python 3.10.17 environment at: .venv-3.10
Resolved 31 packages in 7ms
Installed 31 packages in 64ms
 + filelock==3.20.3
 + fsspec==2026.2.0
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + mpmath==1.3.0
 + networkx==3.4.2
 + numpy==1.26.4
 + nvidia-cublas-cu12==12.8.4.1
 + nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-runtime-cu12==12.8.90
 + nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufile-cu12==1.13.1.3
 + nvidia-curand-cu12==10.3.9.90
 + nvidia-cusolver-cu12==11.7.3.90
 + nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparselt-cu12==0.7.1
 + nvidia-nccl-cu12==2.27.5
 + nvidia-nvjitlink-cu12==12.8.93
 + nvidia-nvshmem-cu12==3.3.20
 + nvidia-nvtx-cu12==12.8.90

In [4]:
x = 10
result = np.array([1, 2, 3])

In [5]:
%%remotecell
import numpy as np
import torch
import sys

print(sys.version)

y = np.array([1, 2, 3])
print(f"Defined x={x}, result={result}")

t = torch.randn(10, 10).cuda()
print(t)

3.11.13 (main, Jun  4 2025, 08:57:30) [GCC 9.4.0]
Defined x=10, result=[1 2 3]
tensor([[-0.3438, -0.3864, -0.1155, -0.8343,  0.0156,  1.5066, -1.3486,  1.3477,
          0.5314, -0.2037],
        [-1.9459, -1.2205, -0.7801, -0.0955,  0.3546, -0.1088, -0.9690, -0.8072,
         -0.3207, -1.4992],
        [ 0.0102,  1.3021, -1.0558,  1.5481,  2.6094, -0.8639,  0.2853,  1.8354,
         -0.0339, -0.6385],
        [ 0.0177, -1.3373,  0.1181, -2.8158,  0.6706,  0.8301,  0.7482,  1.6369,
          0.8053,  1.1903],
        [-1.3742, -1.1771,  0.2372, -1.3392, -0.4936,  0.2257,  0.9330,  0.2934,
          0.4760, -0.8228],
        [-0.3808, -0.0954, -0.7584, -0.2644,  1.0511,  0.7662,  0.6075, -1.2385,
         -1.9772, -0.9169],
        [ 2.4144,  0.3638,  1.0548, -0.0093,  0.5077,  1.6942,  0.9079, -0.1277,
          0.6515,  0.9856],
        [ 1.0781, -0.6505,  0.1848, -0.1404, -0.2462, -0.5394,  1.7267, -1.0849,
          0.4554, -0.7030],
        [-1.6163,  0.6951,  1.7460,  0.9013,  0.6

In [6]:
%%remotecell --profile 3.10

print(sys.version)
print(t)

3.10.17 (main, Apr  9 2025, 08:54:15) [GCC 9.4.0]
tensor([[-0.3438, -0.3864, -0.1155, -0.8343,  0.0156,  1.5066, -1.3486,  1.3477,
          0.5314, -0.2037],
        [-1.9459, -1.2205, -0.7801, -0.0955,  0.3546, -0.1088, -0.9690, -0.8072,
         -0.3207, -1.4992],
        [ 0.0102,  1.3021, -1.0558,  1.5481,  2.6094, -0.8639,  0.2853,  1.8354,
         -0.0339, -0.6385],
        [ 0.0177, -1.3373,  0.1181, -2.8158,  0.6706,  0.8301,  0.7482,  1.6369,
          0.8053,  1.1903],
        [-1.3742, -1.1771,  0.2372, -1.3392, -0.4936,  0.2257,  0.9330,  0.2934,
          0.4760, -0.8228],
        [-0.3808, -0.0954, -0.7584, -0.2644,  1.0511,  0.7662,  0.6075, -1.2385,
         -1.9772, -0.9169],
        [ 2.4144,  0.3638,  1.0548, -0.0093,  0.5077,  1.6942,  0.9079, -0.1277,
          0.6515,  0.9856],
        [ 1.0781, -0.6505,  0.1848, -0.1404, -0.2462, -0.5394,  1.7267, -1.0849,
          0.4554, -0.7030],
        [-1.6163,  0.6951,  1.7460,  0.9013,  0.6030,  0.6490, -1.5314, -1.025

In [7]:
%%remotecell

global result

result = np.concatenate([result, result])
print(result)

[1 2 3 1 2 3]


In [8]:
close_remote()

Deleted virtual environment at /home/ubuntu/.venv-3.11
Remote connection closed.
Deleted virtual environment at /home/ubuntu/.venv-3.10
Remote connection closed.
