In [1]:
from pyremote import remote, remotecell, UvConfig, close_remote
import numpy as np

/home/husein/.local/lib/python3.10/site-packages/paramiko/pkey.py:100: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "cipher": algorithms.TripleDES,
/home/husein/.local/lib/python3.10/site-packages/paramiko/transport.py:259: CryptographyDeprecationWarning: TripleDES has been moved to cryptography.hazmat.decrepit.ciphers.algorithms.TripleDES and will be removed from cryptography.hazmat.primitives.ciphers.algorithms in 48.0.0.
  "class": algorithms.TripleDES,


In [2]:
remote(
    "localhost", 
    "ubuntu", 
    password="ubuntu123", 
    uv=UvConfig(path="~/.venv-3.11", python_version="3.11", install_uv=True, delete_after_done=True), 
    dependencies=["numpy==1.26.4", "pandas==2.2.3", "torch==2.9.1"],
    install_verbose=True,
    jupyter_mode=True,
)

Using CPython 3.11.13 interpreter at: /usr/bin/python3.11
Creating virtual environment at: .venv-3.11
Activate with: source .venv-3.11/bin/activate
Using Python 3.11.13 environment at: .venv-3.11
Resolved 1 package in 0.96ms
Installed 1 package in 2ms
 + cloudpickle==3.1.2
Using Python 3.11.13 environment at: .venv-3.11
Resolved 31 packages in 8ms
Installed 31 packages in 90ms
 + filelock==3.20.3
 + fsspec==2026.1.0
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + mpmath==1.3.0
 + networkx==3.6.1
 + numpy==1.26.4
 + nvidia-cublas-cu12==12.8.4.1
 + nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-runtime-cu12==12.8.90
 + nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufile-cu12==1.13.1.3
 + nvidia-curand-cu12==10.3.9.90
 + nvidia-cusolver-cu12==11.7.3.90
 + nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparselt-cu12==0.7.1
 + nvidia-nccl-cu12==2.27.5
 + nvidia-nvjitlink-cu12==12.8.93
 + nvidia-nvshmem-cu12==3.3.20
 + nvidia-nvtx-cu12==12.8

In [3]:
remote(
    "localhost", 
    "ubuntu", 
    password="ubuntu123", 
    uv=UvConfig(path="~/.venv-3.10", python_version="3.10", install_uv=True, delete_after_done=True), 
    dependencies=["numpy==1.26.4", "pandas==2.2.3", "torch==2.9.1"],
    install_verbose=True,
    jupyter_mode=True,
    jupyter_profile="3.10"
)

Using CPython 3.10.17 interpreter at: /usr/bin/python3.10
Creating virtual environment at: .venv-3.10
Activate with: source .venv-3.10/bin/activate
Using Python 3.10.17 environment at: .venv-3.10
Resolved 1 package in 1ms
Installed 1 package in 1ms
 + cloudpickle==3.1.2
Using Python 3.10.17 environment at: .venv-3.10
Resolved 31 packages in 7ms
Installed 31 packages in 71ms
 + filelock==3.20.3
 + fsspec==2026.1.0
 + jinja2==3.1.6
 + markupsafe==3.0.3
 + mpmath==1.3.0
 + networkx==3.4.2
 + numpy==1.26.4
 + nvidia-cublas-cu12==12.8.4.1
 + nvidia-cuda-cupti-cu12==12.8.90
 + nvidia-cuda-nvrtc-cu12==12.8.93
 + nvidia-cuda-runtime-cu12==12.8.90
 + nvidia-cudnn-cu12==9.10.2.21
 + nvidia-cufft-cu12==11.3.3.83
 + nvidia-cufile-cu12==1.13.1.3
 + nvidia-curand-cu12==10.3.9.90
 + nvidia-cusolver-cu12==11.7.3.90
 + nvidia-cusparse-cu12==12.5.8.93
 + nvidia-cusparselt-cu12==0.7.1
 + nvidia-nccl-cu12==2.27.5
 + nvidia-nvjitlink-cu12==12.8.93
 + nvidia-nvshmem-cu12==3.3.20
 + nvidia-nvtx-cu12==12.8.90

In [4]:
x = 10
result = np.array([1, 2, 3])

In [5]:
%%remotecell
import numpy as np
import torch
import sys

print(sys.version)

y = np.array([1, 2, 3])
print(f"Defined x={x}, result={result}")

t = torch.randn(10, 10).cuda()
print(t)

3.11.13 (main, Jun  4 2025, 08:57:30) [GCC 9.4.0]
Defined x=10, result=[1 2 3]
tensor([[ 6.1146e-01,  2.2552e-01, -7.4423e-01,  2.1329e-01,  1.7878e+00,
          1.6502e+00,  6.1555e-01,  9.6762e-01, -9.2587e-02,  8.1585e-01],
        [ 1.4931e+00, -6.8062e-01, -8.9354e-01,  5.4590e-01,  1.9131e-03,
          2.3486e-02, -1.8477e-01,  4.7742e-02, -6.4516e-01, -1.1166e-01],
        [ 5.0783e-01,  9.5421e-02,  1.0320e+00,  1.0705e+00, -2.7514e-01,
         -2.7833e-01, -1.8243e-01, -2.2620e-01,  1.8950e+00, -4.2753e-01],
        [ 1.2461e+00, -1.3281e+00, -2.1273e+00,  1.2477e+00,  5.9034e-01,
         -9.1703e-01,  3.9618e-01,  2.7257e-01,  3.9846e-01, -2.2619e+00],
        [ 1.8078e+00,  1.0062e+00, -8.1295e-02, -4.7849e-01,  2.8566e-02,
          1.9351e-01,  1.9739e+00,  9.0229e-03,  2.6468e-01,  7.7196e-01],
        [-3.6440e-01, -1.3292e+00,  5.7839e-01, -5.5599e-01, -6.3926e-01,
          1.2966e+00, -7.8355e-01,  4.3229e-01, -6.4102e-01, -8.6305e-02],
        [-8.2536e-01, -1.03

In [6]:
%%remotecell --profile 3.10

import numpy as np
import torch
import sys

print(sys.version)
print(t)

3.10.17 (main, Apr  9 2025, 08:54:15) [GCC 9.4.0]
tensor([[ 6.1146e-01,  2.2552e-01, -7.4423e-01,  2.1329e-01,  1.7878e+00,
          1.6502e+00,  6.1555e-01,  9.6762e-01, -9.2587e-02,  8.1585e-01],
        [ 1.4931e+00, -6.8062e-01, -8.9354e-01,  5.4590e-01,  1.9131e-03,
          2.3486e-02, -1.8477e-01,  4.7742e-02, -6.4516e-01, -1.1166e-01],
        [ 5.0783e-01,  9.5421e-02,  1.0320e+00,  1.0705e+00, -2.7514e-01,
         -2.7833e-01, -1.8243e-01, -2.2620e-01,  1.8950e+00, -4.2753e-01],
        [ 1.2461e+00, -1.3281e+00, -2.1273e+00,  1.2477e+00,  5.9034e-01,
         -9.1703e-01,  3.9618e-01,  2.7257e-01,  3.9846e-01, -2.2619e+00],
        [ 1.8078e+00,  1.0062e+00, -8.1295e-02, -4.7849e-01,  2.8566e-02,
          1.9351e-01,  1.9739e+00,  9.0229e-03,  2.6468e-01,  7.7196e-01],
        [-3.6440e-01, -1.3292e+00,  5.7839e-01, -5.5599e-01, -6.3926e-01,
          1.2966e+00, -7.8355e-01,  4.3229e-01, -6.4102e-01, -8.6305e-02],
        [-8.2536e-01, -1.0366e+00, -3.6685e-01, -1.0335e

In [7]:
%%remotecell

import numpy as np

global result

result = np.concatenate([result, result])
print(result)

[1 2 3 1 2 3]


In [8]:
close_remote()

Deleted virtual environment at /home/ubuntu/.venv-3.11
Remote connection closed.
Deleted virtual environment at /home/ubuntu/.venv-3.10
Remote connection closed.
